name: CI

on:
  push:
    branches:
      - develop  # Change this to the branch you want to trigger the workflow on

jobs:


  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Dev
        run: |
          ls
          pwd
          SEMVERTAG=123
          cat values.yaml 
          sed -i -e 's/__IMAGETAG__/'"$SEMVERTAG"'/g' values.yaml 
          cat values.yaml 
      - name: Auto Commit
        run: |
        
         git status
         git add .
         git status
         git branch


    
